# Generated by Django 4.0.3 on 2022-03-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='User',
            new_name='user',
        ),
    ]
